name = "SymmetricTensorProof"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["SymmetricTensorProof"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "ln_messagepack"
git = "https://github.com/ItsMeForLua/ln_messagepack"
rev = "main"

[[lean_lib]]
name = "SymmetricTensorProof"
